PREREQUISITES = [
    {
        "id": "python-core",
        "title": "Python Core",
        "icon": "🐍",
        "level": "Foundation",
        "description": "Control flow, functions, scope, comprehensions, exceptions, modules, and clean Python syntax.",
        "why": "DSA code is much easier when the language itself is automatic.",
        "topics": [
            "Variables and data types",
            "if / elif / else",
            "for and while loops",
            "Functions and return values",
            "Scope and mutability",
            "Comprehensions",
            "Exceptions",
            "Modules and imports",
        ],
    },
    {
        "id": "builtins",
        "title": "Built-in Data Structures",
        "icon": "🧰",
        "level": "Essential",
        "description": "Know lists, tuples, dictionaries, sets, strings, and their common operations before building custom structures.",
        "why": "Many interview patterns are really about choosing the correct built-in structure.",
        "topics": [
            "list",
            "tuple",
            "dict",
            "set",
            "str",
            "collections.deque",
            "Counter and defaultdict",
        ],
    },
    {
        "id": "big-o",
        "title": "Big O & Complexity",
        "icon": "📈",
        "level": "Essential",
        "description": "Estimate how runtime and memory grow as input size grows.",
        "why": "Correct code is only half the job; DSA asks whether the solution scales.",
        "topics": [
            "O(1)",
            "O(log n)",
            "O(n)",
            "O(n log n)",
            "O(n²)",
            "Time vs space complexity",
            "Best / average / worst case",
            "Dominant terms",
        ],
    },
    {
        "id": "memory",
        "title": "Memory, References & Parameters",
        "icon": "🧠",
        "level": "Core Mental Model",
        "description": "Understand names, objects, references, mutability, stack frames, and what function arguments really do.",
        "why": "Linked structures, recursion, and debugging become clearer when references make sense.",
        "topics": [
            "Names reference objects",
            "Mutable vs immutable values",
            "Aliasing",
            "Shallow vs deep copy",
            "Function arguments",
            "Call stack mental model",
        ],
    },
    {
        "id": "oop",
        "title": "OOP for Data Structures",
        "icon": "🧱",
        "level": "Implementation",
        "description": "Use classes to model nodes, containers, invariants, and reusable behavior.",
        "why": "Linked lists, trees, heaps, and graphs are easier to build with clean object models.",
        "topics": [
            "Classes and instances",
            "__init__",
            "Instance attributes",
            "Methods",
            "__repr__",
            "Encapsulation",
            "Composition",
            "Dataclasses",
        ],
    },
    {
        "id": "recursion",
        "title": "Recursion Foundations",
        "icon": "🪆",
        "level": "Algorithmic",
        "description": "Break a problem into smaller versions of itself with a guaranteed stopping condition.",
        "why": "Trees, divide-and-conquer, DFS, backtracking, and dynamic programming all build on this idea.",
        "topics": [
            "Base case",
            "Recursive case",
            "Call stack",
            "Return unwinding",
            "Stack depth",
            "Recurrence intuition",
        ],
    },
    {
        "id": "patterns",
        "title": "Problem-Solving Patterns",
        "icon": "🧩",
        "level": "Bridge to DSA",
        "description": "Practice reusable ways to organize loops, state, and data.",
        "why": "Patterns reduce the gap between knowing a data structure and solving a problem with it.",
        "topics": [
            "Linear scan",
            "Two pointers",
            "Sliding window",
            "Frequency counting",
            "Prefix accumulation",
            "Fast / slow pointers",
            "Binary search thinking",
        ],
    },
    {
        "id": "tooling",
        "title": "Testing, Debugging & Git",
        "icon": "🧪",
        "level": "Engineering",
        "description": "Prove code works, isolate bugs, and present the project professionally.",
        "why": "A portfolio project should demonstrate engineering habits, not just algorithm answers.",
        "topics": [
            "pytest",
            "Assertions",
            "Edge cases",
            "Type hints",
            "Docstrings",
            "Git commits",
            "GitHub Actions",
        ],
    },
]

BUILTIN_COMPLEXITIES = [
    {"structure": "list", "operation": "index access", "average": "O(1)", "note": "Direct indexed lookup."},
    {"structure": "list", "operation": "append", "average": "O(1) amortized", "note": "Occasional resize makes one append expensive."},
    {"structure": "list", "operation": "insert/delete front", "average": "O(n)", "note": "Elements must shift."},
    {"structure": "list", "operation": "membership", "average": "O(n)", "note": "Linear scan in the general case."},
    {"structure": "dict", "operation": "lookup/insert/delete", "average": "O(1)", "note": "Hash table; worst case can degrade."},
    {"structure": "set", "operation": "membership/add/remove", "average": "O(1)", "note": "Hash table-backed."},
    {"structure": "tuple", "operation": "index access", "average": "O(1)", "note": "Immutable sequence."},
    {"structure": "str", "operation": "index access", "average": "O(1)", "note": "Character lookup by position."},
    {"structure": "str", "operation": "concatenate repeatedly", "average": "Can approach O(n²)", "note": "Strings are immutable; repeated rebuilding can be costly."},
]
